# database configurations
source:
  host: "db_host"
  port: "db_port"
  database: "db_name"
  user: "db_user"
  password: "db_password"

destination:
  host: "db_host"
  port: "db_port"
  database: "db_name"
  user: "db_user"
  password: "db_password"

# tables and columns to sync
#
tables:
  - name: contacts
    primary_key: id
    columns:
      - name: address_book_id 
  - name: contacts_user_links 
    primary_key: id
    columns:
      - name: user_id 
      - name: contact_id
      - name: contact_order 
